#Constantes enviadas por integrador.
_CONF_INI = 0XC0
_ESTADO = 0XC1
_CONF_PROD = 0XC2
_CAMBIAR_PRECIOS = 0XC3
_ACT_HORA = 0XC4
_RESET = 0XC5
_REPORTE_VENTA = 0XC6
_PET_PROD_CAN = 0XC7
_IMPRIMIR = 0XCC
_PETAUTVENTA = 0XC8
_AUTORIZARVENTA = 0XC9
_DATOSTURNO = 0XCA
_DATOSPRODCAN = 0XCB
_VENTACANASTA = 0XCD
_AUTVENTCAN = 0XCE
_CONFIRTURNO = 0XCF
#Tipos de reset que envia el integrador.
_RES_VENTA  = 0x01
_RES_VENTA_CANASTA = 0x02   
_RES_CANCELADA = 0x03
_RES_REIMPRESION = 0x04
_RES_CONSIG = 0x06
_OBL_CONSIGNAR = 0x07
_RES_CONSIGNAR = 0x08
_RES_FPAGOS = 0x09
_PET_CERRAR_TUR = 0XD0
_CONSIG = 0XD2
_FORMAPAGO = 0XD4
_NOM_PROD = 0XD5
_OBT_INFO = 0XD6
#Contantes de respuesta hacia el integrador.
_RCONF_INI = 0XA0
_RESTADO = 0XA1
_RCONF_PROD = 0XA2
_RCAMBIAR_PRECIOS = 0XA3 
_RACT_HORA = 0XA4
_RRESET = 0XA5 
_REPORTE_VENTA = 0XA6
_PET_PROD_CAN = 0XA7
_IMPRIMIR = 0XAC
_PETAUTVENTA = 0XA8
_AUTORIZARVENTA = 0XA9
_DATOSTURNO = 0XAA
_DATOSPRODCAN = 0XAB
_VENTACANASTA = 0XAD
_AUTVENTCAN = 0XAE
_CONFIRTURNO = 0XAF
_RPET_CERRAR_TUR = 0XB0
_RCONSIG = 0XB1
_RFORMAPAGO = 0XB3
_RNOM_PROD = 0XB5


	


